name: sgs
description: A Flutter application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  equatable: ^1.2.6
  bloc_test: ^7.1.0
  bloc: ^6.1.1
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
